version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    depends_on:
      - products


  products:
    build:
      context: ./backend
      dockerfile: products/Dockerfile
    ports:
      - "5001:5001"
    volumes:
      - ./backend/products:/app
      - products_db:/app/instance


  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev -- --host
    depends_on:
      - backend

volumes:
  products_db: