version: '3'

services:
  jaeger:
    container_name: jaeger
    image: jaegertracing/all-in-one:latest
    ports:
      - "4318:4318"
      - "16686:16686"
    environment:
      COLLECTOR_OTLP_ENABLED: 1
      SPAN_STORAGE_TYPE: elasticsearch
      ES_SERVER_URLS: http://elasticsearch:9200

  collector:
    container_name: collector
    image: otel/opentelemetry-collector-contrib:latest
    ports:
      - "4320:4320"
      - "4321:4321"
      - "9464:9464"
    volumes:
      - ./collector-config.yaml:/etc/otel/config.yaml
    command: ["--config=/etc/otel/config.yaml"]
    depends_on:
      - jaeger

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    depends_on:
      - products
      - checkout
      - orders
      - collector

  products:
    build:
      context: ./backend
      dockerfile: products/Dockerfile
    ports:
      - "5001:5001"
    volumes:
      - ./backend/products:/app
      - products_db:/app/instance
    depends_on:
      - collector

  orders:
    build:
      context: ./backend
      dockerfile: orders/Dockerfile
    ports:
      - "5002:5002"
    volumes:
      - ./backend/orders:/app
      - orders_db:/app/instance
    depends_on:
      - products
      - collector

  checkout:
    build:
      context: ./backend
      dockerfile: checkout/Dockerfile
    ports:
      - "5003:5003"
    volumes:
      - ./backend/checkout:/app
    depends_on:
      - products
      - orders
      - collector

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev -- --host
    depends_on:
      - backend
      - collector

  payment:
    build:
      context: ./backend
      dockerfile: payment/Dockerfile
    ports:
      - "5004:5004"
    volumes:
      - ./backend/payment:/app
    depends_on:
      - orders
      - collector

  cart:
    build:
      context: ./backend
      dockerfile: cart/Dockerfile
    ports:
      - "5005:5005"
    volumes:
      - ./backend/cart:/app
      - cart_db:/app/instance
    depends_on:
      - products
      - collector


volumes:
  products_db:
  orders_db:
  cart_db: