apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkout
  namespace: rmalves
spec:
  replicas: 1
  selector:
    matchLabels:
      app: checkout
  template:
    metadata:
      labels:
        app: checkout
    spec:
      containers:
        - name: checkout
          image: momosuke07/checkout:latest
          ports:
            - containerPort: 5003

---

apiVersion: v1
kind: Service
metadata:
  name: checkout
  namespace: rmalves
spec:
  selector:
    app: checkout
  ports:
    - protocol: TCP
      port: 5003
      targetPort: 5003
  type: ClusterIP
