apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart 
  namespace: rmalves 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cart 
  template:
    metadata:
      labels:
        app: cart 
    spec:
      containers:
        - name: cart
          image: momosuke07/cart:latest 
          ports:
            - containerPort: 5005
---

apiVersion: v1
kind: Service
metadata:
  name: cart
  namespace: rmalves
spec:
  selector:
    app: cart
  ports:
    - protocol: TCP
      port: 5005
      targetPort: 5005
  type: ClusterIP