apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders
  namespace: rmalves
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders
  template:
    metadata:
      labels:
        app: orders
    spec:
      containers:
        - name: orders
          image: momosuke07/orders:latest
          ports:
            - containerPort: 5002
---
apiVersion: v1
kind: Service
metadata:
  name: orders
  namespace: rmalves
spec:
  selector:
    app: orders
  ports:
    - protocol: TCP
      port: 5002
      targetPort: 5002
  type: ClusterIP
