apiVersion: apps/v1
kind: Deployment
metadata:
  name: loadgenerator
  namespace: rmalves
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loadgenerator
  template:
    metadata:
      labels:
        app: loadgenerator
    spec:
      containers:
        - name: loadgenerator
          image: momosuke07/loadgenerator:latest
          ports:
            - containerPort: 5009

---

apiVersion: v1
kind: Service
metadata:
  name: loadgenerator
  namespace: rmalves
spec:
  selector:
    app: loadgenerator
  ports:
    - protocol: TCP
      port: 5009
      targetPort: 5009
  type: ClusterIP
