apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: rmalves
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        # Container da aplicação Flask
        - name: backend
          image: momosuke07/backend:latest
          ports:
            - containerPort: 5000
          env:
            - name: DATABASE_URL
              value: postgresql://postgres:postgres@localhost:5432/meubanco
          # opcional: se precisar de variáveis extras ou volume mounts
          
        # Sidecar do PostgreSQL
        - name: postgres
          image: postgres:16
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRES_DB
              value: meubanco
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data

      volumes:
        - name: postgres-data
          emptyDir: {}   # dados não persistem, perfeito para testes/dev

---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: rmalves
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP
