apiVersion: apps/v1
kind: Deployment
metadata:
  name: products
  namespace: rmalves
spec:
  replicas: 1
  selector:
    matchLabels:
      app: products
  template:                  # <-- corrigido: template é obrigatório
    metadata:
      labels:
        app: products
    spec:
      containers:
        - name: products    # <-- nome do container
          image: momosuke07/products:latest
          ports:
            - containerPort: 5001
---
apiVersion: v1
kind: Service
metadata:
  name: products
  namespace: rmalves
spec:
  selector:
    app: products
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
  type: ClusterIP
