apiVersion: apps/v1
kind: Deployment
metadata:
  name: products
  namespace: rmalves
spec:
  replicas: 3
  selector:
    matchLabels:
      app: products
  template:                  # <-- corrigido: template é obrigatório
    metadata:
      labels:
        app: products
    spec:
      containers:
        - name: products    # <-- nome do container
          image: momosuke07/products:latest
          ports:
            - containerPort: 5001
          env:
            - name: DATABASE_URL
              value: postgresql://postgres:postgres@localhost:5432/meubanco
          # opcional: se precisar de variáveis extras ou volume mounts
          
        # Sidecar do PostgreSQL
        - name: postgres
          image: postgres:16
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRES_DB
              value: meubanco
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data

      volumes:
        - name: postgres-data
          emptyDir: {}   # dados não persistem, perfeito para testes/dev
---
apiVersion: v1
kind: Service
metadata:
  name: products
  namespace: rmalves
spec:
  selector:
    app: products
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
  type: ClusterIP
